# Generated by Django 3.2.25 on 2025-07-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telessaude_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagemconsulta',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='consultas/anexos/2025-07-01/'),
        ),
    ]
