# Generated by Django 3.2.25 on 2025-07-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telessaude_web', '0002_alter_mensagemconsulta_anexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
