# Generated by Django 3.2.25 on 2025-07-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telessaude_web', '0003_alter_consulta_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagemconsulta',
            name='conteudo',
            field=models.TextField(blank=True),
        ),
    ]
