# Generated by Django 3.2.25 on 2025-07-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telessaude_web', '0004_alter_mensagemconsulta_conteudo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='mensagemconsulta',
            name='conteudo',
            field=models.TextField(),
        ),
    ]
