# Generated by Django 3.2.25 on 2025-07-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telessaude_web', '0005_auto_20250701_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagemconsulta',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='consultas/anexos/2025-07-02/'),
        ),
    ]
